name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  NODE_VERSION: 24
  PNPM_VERSION: 10.14.0

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: 'â¬‡ï¸ Checkout Repo'
        uses: actions/checkout@v4

      - name: 'ðŸŸ¨ Install pnpm' 
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: 'ðŸ’š Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: 'ðŸ“¦ Install Packages'
        run: pnpm install

      - name: 'ðŸ”„ Create Release Pull Request or Publish'
        id: changesets
        uses: changesets/action@v1
        with:
          createGithubReleases: true
          publish: pnpm run publish
          version: pnpm run version
          title: >-
            ${{ github.ref_name == 'main' && 'chore(release): publish a new stable version' || 'chore(release): publish a new pre-release version' }}
          commit: >-
            ${{ github.ref_name == 'main' && 'chore(release): publish a new stable version' || 'chore(release): publish a new pre-release version' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'ðŸš€ Publish'
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: pnpm run publish